amino_acids_from_codon = {
    'GCT': {'name': 'Alanine', 'code': 'A'},
    'GCC': {'name': 'Alanine', 'code': 'A'},
    'GCA': {'name': 'Alanine', 'code': 'A'},
    'GCG': {'name': 'Alanine', 'code': 'A'},
    'TGT': {'name': 'Cysteine', 'code': 'C'},
    'TGC': {'name': 'Cysteine', 'code': 'C'},
    'GAT': {'name': 'Aspartic acid', 'code': 'D'},
    'GAC': {'name': 'Aspartic acid', 'code': 'D'},
    'GAA': {'name': 'Glutamic acid', 'code': 'E'},
    'GAG': {'name': 'Glutamic acid', 'code': 'E'},
    'TTT': {'name': 'Phenylalanine', 'code': 'F'},
    'TTC': {'name': 'Phenylalanine', 'code': 'F'},
    'GGT': {'name': 'Glycine', 'code': 'G'},
    'GGC': {'name': 'Glycine', 'code': 'G'},
    'GGA': {'name': 'Glycine', 'code': 'G'},
    'GGG': {'name': 'Glycine', 'code': 'G'},
    'CAT': {'name': 'Histidine', 'code': 'H'},
    'CAC': {'name': 'Histidine', 'code': 'H'},
    'ATT': {'name': 'Isoleucine', 'code': 'I'},
    'ATC': {'name': 'Isoleucine', 'code': 'I'},
    'ATA': {'name': 'Isoleucine', 'code': 'I'},
    'AAA': {'name': 'Lysine', 'code': 'K'},
    'AAG': {'name': 'Lysine', 'code': 'K'},
    'TTA': {'name': 'Leucine', 'code': 'L'},
    'TTG': {'name': 'Leucine', 'code': 'L'},
    'CTT': {'name': 'Leucine', 'code': 'L'},
    'CTC': {'name': 'Leucine', 'code': 'L'},
    'CTA': {'name': 'Leucine', 'code': 'L'},
    'CTG': {'name': 'Leucine', 'code': 'L'},
    'ATG': {'name': 'Methionine', 'code': 'M'},
    'AAT': {'name': 'Asparagine', 'code': 'N'},
    'AAC': {'name': 'Asparagine', 'code': 'N'},
    'CCT': {'name': 'Proline', 'code': 'P'},
    'CCC': {'name': 'Proline', 'code': 'P'},
    'CCA': {'name': 'Proline', 'code': 'P'},
    'CCG': {'name': 'Proline', 'code': 'P'},
    'CAA': {'name': 'Glutamine', 'code': 'Q'},
    'CAG': {'name': 'Glutamine', 'code': 'Q'},
    'CGT': {'name': 'Arginine', 'code': 'R'},
    'CGC': {'name': 'Arginine', 'code': 'R'},
    'CGA': {'name': 'Arginine', 'code': 'R'},
    'CGG': {'name': 'Arginine', 'code': 'R'},
    'AGA': {'name': 'Arginine', 'code': 'R'},
    'AGG': {'name': 'Arginine', 'code': 'R'},
    'TCT': {'name': 'Serine', 'code': 'S'},
    'TCC': {'name': 'Serine', 'code': 'S'},
    'TCA': {'name': 'Serine', 'code': 'S'},
    'TCG': {'name': 'Serine', 'code': 'S'},
    'AGT': {'name': 'Serine', 'code': 'S'},
    'AGC': {'name': 'Serine', 'code': 'S'},
    'ACT': {'name': 'Threonine', 'code': 'T'},
    'ACC': {'name': 'Threonine', 'code': 'T'},
    'ACA': {'name': 'Threonine', 'code': 'T'},
    'ACG': {'name': 'Threonine', 'code': 'T'},
    'TGA': {'name': 'Selenocysteine', 'code': 'U'},
    'GTT': {'name': 'Valine', 'code': 'V'},
    'GTC': {'name': 'Valine', 'code': 'V'},
    'GTA': {'name': 'Valine', 'code': 'V'},
    'GTG': {'name': 'Valine', 'code': 'V'},
    'TGG': {'name': 'Tryptophan', 'code': 'W'},
    'TAT': {'name': 'Tyrosine', 'code': 'Y'},
    'TAC': {'name': 'Tyrosine', 'code': 'Y'},
    # Stops
    # 'TAA': None,
    # 'TAG': None,
    # 'TGA': None,
    # Start
    # 'ATG': None,

}
