amino_acids_from_code = {
    'A': {'name': 'Alanine', 'codons': ['GCT', 'GCC', 'GCA', 'GCG']},
    'C': {'name': 'Cysteine', 'codons': ['TGT', 'TGC']},
    'D': {'name': 'Aspartic acid', 'codons': ['GAT', 'GAC']},
    'E': {'name': 'Glutamic acid', 'codons': ['GAA', 'GAG']},
    'F': {'name': 'Phenylalanine', 'codons': ['TTT', 'TTC']},
    'G': {'name': 'Glycine', 'codons': ['GGT', 'GGC', 'GGA', 'GGG']},
    'H': {'name': 'Histidine', 'codons': ['CAT', 'CAC']},
    'I': {'name': 'Isoleucine', 'codons': ['ATT', 'ATC', 'ATA']},
    'K': {'name': 'Lysine', 'codons': ['AAA', 'AAG']},
    'L': {'name': 'Leucine', 'codons': ['TTA', 'TTG', 'CTT', 'CTC', 'CTA', 'CTG']},
    'M': {'name': 'Methionine', 'codons': ['ATG']},
    'N': {'name': 'Asparagine', 'codons': ['AAT', 'AAC']},
    'O': {'name': 'Pyrrolysine', 'codons': ['TAG']},
    'P': {'name': 'Proline', 'codons': ['CCT', 'CCC', 'CCA', 'CCG']},
    'Q': {'name': 'Glutamine', 'codons': ['CAA', 'CAG']},
    'R': {'name': 'Arginine', 'codons': ['CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG']},
    'S': {'name': 'Serine', 'codons': ['TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC']},
    'T': {'name': 'Threonine', 'codons': ['ACT', 'ACC', 'ACA', 'ACG']},
    'U': {'name': 'Selenocysteine', 'codons': ['TGA']},
    'V': {'name': 'Valine', 'codons': ['GTT', 'GTC', 'GTA', 'GTG']},
    'W': {'name': 'Tryptophan', 'codons': ['TGG']},
    'Y': {'name': 'Tyrosine', 'codons': ['TAT', 'TAC']},
}
